---
kind: ConfigMap
apiVersion: v1
metadata:
  # namespace: rocketmq
  name: configmap-rocketmq-broker-slave-prod
data:
  NAME_SRV_ADDR: 'statefulset-rocketmq-namesrv-prod-0.service-rocketmq-namesrv-prod.rocketmq:9876;statefulset-rocketmq-namesrv-prod-1.service-rocketmq-namesrv-prod.rocketmq:9876'
  BROKER_ID: '1'
  BROKER_ROLE: 'SLAVE'
  STATEFULSET_NAME: 'statefulset-rocketmq-broker-slave-prod'
  SEND_MESSAGE_THREAD_POOL_NUMS: '128'
---
kind: Service
apiVersion: v1
metadata:
  namespace: rocketmq
  name: service-rocketmq-broker-slave-prod
  labels:
    app: service-rocketmq-broker-slave-prod
spec:
  ports:
    - name: rocketmq-port-10909
      protocol: TCP
      port: 10909
      targetPort: 10909
    - name: rocketmq-port-10911
      protocol: TCP
      port: 10911
      targetPort: 10911
  selector:
    app: pod-rocketmq-broker-slave-prod
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: rocketmq
  name: statefulset-rocketmq-broker-slave-prod
  labels:
    app: statefulset-rocketmq-broker-slave-prod
spec:
  replicas: 1
  serviceName: service-rocketmq-broker-slave-prod
  selector:
    matchLabels:
      app: pod-rocketmq-broker-slave-prod
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-rocketmq-broker-slave-prod
    spec:
      nodeSelector:
        node-role.kubernetes.io/rocketmq: 'true'

      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/szss/rocketmq-broker:v4.3.1
          securityContext:
            privileged: true
          imagePullPolicy: Always
          name: container-rocketmq-broker-slave-prod
          ports:
            - protocol: TCP
              containerPort: 10909
            - protocol: TCP
              containerPort: 10911

          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 1
              memory: 2Gi

          envFrom:
            - configMapRef:
                name: configmap-rocketmq-broker-slave-prod

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          volumeMounts:
            - name: host-volume-rocketmq-broker-slave-prod
              mountPath: /opt/rocketmq/store

          readinessProbe:
            tcpSocket:
              port: 10909
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 10909
            initialDelaySeconds: 120
            periodSeconds: 10

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - pod-rocketmq-broker-slave-prod
                topologyKey: kubernetes.io/hostname

      dnsPolicy: ClusterFirst
      restartPolicy: Always

      volumes:
        - name: host-volume-rocketmq-broker-slave-prod
          hostPath:
            path: /mnt/data/rocketmq-slave
  ---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    namespace: rocketmq
    name: mq-store-b-s-pv
    labels:
      pv: mq-store-b-s-pv
  spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: nfs
    nfs:
      path: /mnt/hgfs/rokermq/store-b-s
      server: 192.168.88.138
  ---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: rocketmq
    name: mq-store-b-s-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: nfs
    selector:
      matchLabels:
        pv: mq-store-b-s-pv
